# Github Action
name: 'Report Issue on Jira VULN Mgmt'
description: 'Report an issue on a Jira Project e.g. VULN-123'
inputs:
  format-type:
    required: true
  artifact-name:
    required: true
  finding-source:
    required: true
  affected-component:
    required: true
  env-api-host:
    required: true
  env-jira-access-token:
    required: true
  reporter-email:
    required: true
outputs:
  blah:
    description: 'not used'
    value: ${{ steps.blah.outputs.blah }}
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}

    - name: Install python dependencies
      shell: bash
      run: python3 -m pip install -r ${{ github.action_path }}/requirements.txt
      
    - name: Load environment variables
      shell: bash
      run: |
        echo "API_REPORTER_EMAIL=${{ inputs.reporter-email }}" >> $GITHUB_ENV
        echo "API_ACCESS_TOKEN=${{ inputs.env-jira-access-token }}" >> $GITHUB_ENV
        echo "API_HOSTNAME=${{ inputs.env-api-host }}" >> $GITHUB_ENV

    - name: Debug echo env
      shell: bash
      run: echo $API_HOSTNAME
      
    - name: Python script to report findings from sarif results
      shell: bash
      run: python3 ${{ github.action_path }}/report_issue.py -t ${{ inputs.format-type }} -f ${{ inputs.artifact-name }} -c ${{ inputs.affected-component }} -s ${{ inputs.finding-source}} -r ${{ inputs.reporter-email }}

      