name: Jira Vuln Management Reporting Workflow

on:
  workflow_call:
    inputs:
      trivy-results:
        required: true
        type: string

jobs:
  test-called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, you have called a workflow?"

      - name: Print output (testing only)
        run: echo "${{inputs.trivy-results}}"
