name: Jira Vuln Management Reporting Workflow

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  jira-vuln-reporting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: inputs.artifact-name

      - name: Python script to report findings from trivy-results.sarif
        run: python3 sarif_to_jira_action.py 
