name: Jira Vuln Management Reporting Workflow

on:
  workflow_call:
    inputs:
      trivy-results:
        required: true
        type: string

jobs:
  test-called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, you have called a workflow?"

      - name: (DEBUG) Print output
        run: cat "${{inputs.trivy-results}}" >> trivy-results.sarif
      
      - name: Python script to report findings from trivy-results.sarif
        run: ls -alh
